sudo: false
language: node_js
node_js:
  - '8'
before_install:
  - mysql -e 'CREATE DATABASE disject_unittest;'
install:
  - npm i npminstall && npminstall
services:
  - mysql
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov